from __future__ import annotations

from dataclasses import dataclass, field
from typing import TypedDict, List, Optional, Dict, Any

from langgraph.graph import add_messages
from typing_extensions import Annotated


import operator
from dataclasses import dataclass, field
from typing_extensions import Annotated


class LedgerEntry(TypedDict):
    task_id: str
    description: str
    findings_summary: str  # The concise (1-2 sentence) LLM-generated summary for this task
    detailed_snippets: Optional[List[str]]  # List of relevant web_research_result strings
    citations_for_snippets: Optional[List[Dict[str, str]]]  # Maps snippets to sources


class OverallState(TypedDict):
    messages: Annotated[list, add_messages]
    user_query: str  # Store original user question
    plan: list  # Store task plan generated by planner_node
    current_task_pointer: int  # Point to current task in plan
    executed_search_queries: Annotated[list, operator.add]  # Renamed from search_query
    web_research_result: Annotated[list, operator.add]
    sources_gathered: Annotated[list, operator.add]
    initial_search_query_count: int
    max_research_loops: int
    research_loop_count: int
    reasoning_model: str
    
    # --- Day 2 additions for multi-task iteration ---
    ledger: Annotated[List[LedgerEntry], operator.add]  # Records of completed task findings
    global_summary_memory: Annotated[List[str], operator.add]  # Cross-task memory accumulation
    
    # --- Day 3 additions for richer synthesis ---
    current_task_detailed_findings: Annotated[List[Dict[str, Any]], operator.add]  # Temporary storage for current task's detailed findings
    task_specific_results: Annotated[List[Dict[str, Any]], operator.add]  # Task-specific research results with task_id
    final_report_markdown: Optional[str]  # The final synthesized report
    
    # --- Reflection结果字段 ---
    reflection_is_sufficient: Optional[bool]  # reflection判断的信息充足性
    reflection_knowledge_gap: Optional[str]  # reflection识别的知识差距
    reflection_follow_up_queries: Optional[List[str]]  # reflection建议的follow-up查询
    number_of_ran_queries: Optional[int]  # 已执行的查询数量
    
    # --- 增强版评估结果字段 ---
    evaluation_is_sufficient: Optional[bool]  # 最终评估的信息充足性
    evaluation_should_continue: Optional[bool]  # 是否应该继续研究
    evaluation_follow_up_queries: Optional[List[str]]  # 评估建议的follow-up查询
    evaluation_research_complete: Optional[bool]  # 研究是否完成
    evaluation_enhancement_boost: Optional[int]  # 内容增强带来的提升度
    
    # --- 智能内容增强字段 ---
    enhancement_decision: Optional[Dict[str, Any]]  # 增强决策结果
    enhancement_status: Optional[str]  # "skipped", "completed", "failed", "error", "analyzing"
    enhanced_content_results: Optional[List[Dict[str, Any]]]  # Firecrawl增强内容结果
    enhanced_sources_count: Optional[int]  # 成功增强的源数量
    enhancement_error: Optional[str]  # 增强过程中的错误信息


class ReflectionState(TypedDict):
    is_sufficient: bool
    knowledge_gap: str
    follow_up_queries: Annotated[list, operator.add]
    research_loop_count: int
    number_of_ran_queries: int
    plan: list
    current_task_pointer: int


class Query(TypedDict):
    query: str
    rationale: str


class QueryGenerationState(TypedDict):
    query_list: list[Query]
    plan: list
    current_task_pointer: int


class WebSearchState(TypedDict):
    search_query: str
    id: str
    current_task_id: str


@dataclass(kw_only=True)
class SearchStateOutput:
    running_summary: str = field(default=None)  # Final report
